STORAGE: 
  ENGINE: POSTGRES
  HOST: localhost
  PORT: 5432
  NAME: recipes
  USERNAME: recipez

CACHE:
  HOST: localhost
  PORT: 6379
  PASSWORD: recipez
  DB: recipez

INDEX:
  PORT: 9201

SERVER:
  HOST: localhost
  PORT: 8080